version: "3"
services:

  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.21.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  appium:
    image: appium/appium:latest
    container_name: appium
    restart: always
    privileged: true
    ports:
      - "4723:4723"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
      - /dev/kvm:/dev/kvm
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium-hub
      - SELENIUM_PORT=4444
